// react-frontend/src/component/footer/FooterComponent.js
import React, {Component} from 'react';


class FooterComponent extends Component {
   

	  
     
   
	render(){	
		  return  <footer  className="d-flex justify-content-center" >
                     <div className="copyright"  >
                        <div className={ (!(localStorage.getItem("jwt") == null))  ?  "padding-auth" : "padding-nauth"} >
				            <p>
					           <i><span>{ new Date().getFullYear() }</span> . <a  style={{ color: "crimson" }} href="mailto:farouk.bengarssallah@gmail.com" >Farouk BEN GHARSSALLAH</a></i> 
					     
					        </p>
					
			            </div> 
	                  </div> 		   
                   </footer>;    
				}
    }

export default FooterComponent;

// angular-frontend/src/app/component/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {

  
	   
  getYear() {
	    return new Date().getFullYear();
       }
	   
  public authentificated(): boolean {
			if (localStorage.getItem("jwt")) {
			  return true
			} else {
			  return false;
			};
		  }
		  
}

<footer  class="d-flex justify-content-center" >
       <div class="copyright"  >
          <div class="{'padding-auth' : authentificated(), 'padding-nauth': !authentificated()}" >
				    <p>
					     <i><span>{{ getYear() }}</span> . <a  style="color: crimson;" href="mailto:farouk.bengarssallah@gmail.com">Farouk BEN GHARSSALLAH</a></i> 
					     
					</p>
					
			   </div> 
	    </div> 		   
</footer>
