// angular-frontend/src/app/component/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { LoginService } from '../../services/login.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private loginService:LoginService) { }

   ngOnInit() {}
  
  
  
     login(login, password){
		  /* this.loginService.login(login, password)
		    .subscribe((res: any) => {
					 this.etfs = res.data;}, 
					    (err) => {console.log(err)});  */
		localStorage.setItem("jwt", "jwt");
		localStorage.setItem("expire", "jwt");				
          }

}

   <div class="container-fluid">
		<div class="row"  style="paddingTop: 15%;">
			<div class="col-md-4 offset-md-1 col-sm-12">
				<div class="card">
					<div>
						<h3 class="panel-title text-center" >Provide your credentials</h3>
					</div>
					<div class="card-body">
								<fieldset>
									<div class="form-group">
										<input class="form-control" placeholder="login" [ngModel]="login" type="text" value="" />
									</div>
									<div class="form-group">
										<input class="form-control" placeholder="password" [ngModel]="password" type="password" value=""  />
									</div>
									
									<button class="btn btn-lg btn-info btn-block" type="button" (click)="login(login, password)"  >
										connect <i class="fa fa-check" ></i>
									</button>
								</fieldset>
							</div>
						</div>
					</div>
			   </div>
	   </div>

// react-frontend/src/component/login/LoginComponent.js
import React, {Component} from 'react';
import axios from 'axios';


class LoginComponent extends Component {
	   
   constructor() {
            super();
			this.state = {
				login:'',
                password:''
			        };
       }
	   
	componentDidMount(){
            
       }	
	   
	   login(e){
			/* axios.post('http://localhost:8080/auth/login', {
										 "login" : this.state.username,
										 "password" : this.state.password
										})
			      .then(function (response) {
			                 console.log(response);
			                 if(response.data.code == 200){
			                        console.log("Login successfull");
									localStorage.setItem("jwt", response.data.jwt);
									localStorage.setItem("expire", response.data.expireAt);
			                           }
			                 else if(response.data.code == 204){
			                         console.log("Username password do not match");
			                         let msg = <div  className="text-center" style="padding-top: 10px;"> 
					                                 <span  className="text-center redvl" >Username password do not match</span>
					                           </div>
			                                 }
			                 else{
			                        console.log("Username does not exists");
			                        let msg = 	<div  className="text-center" style="padding-top: 10px;">
			                                          <span  className="text-center redvl" >Username does not exists</span>
			                                    </div>;
			                               }
			                     })
			     .catch(function (error) {
			                 console.log(error);
			          });  */
			localStorage.setItem("jwt", "jwt");
			localStorage.setItem("expire", "jwt");
			this.props.check(true);
          }
		  
		  
		  
		  
		 


    
	 
	render(){
		  
		  return (
				 <div className="container-fluid">
			    <div className="row"  style={{ paddingTop: "15%" }}>
					<div className="col-md-4 offset-md-1 col-sm-12">
			    		<div className="card">
						  	<div>
						    	<h3 className="panel-title text-center" >Provide your credentials</h3>
 						 	</div>
						  	<div className="card-body">
					                    <fieldset>
								    		<div className="form-group">
								    			<input className="form-control" placeholder="login" id="login" type="text" value="" 
  											   onChange = {(e, newValue) => this.setState({login : newValue})}	/>
								    		</div>
								    		<div className="form-group">
								    			<input className="form-control" placeholder="password" id="password" type="password" value="" 
												onChange = {(e, newValue) => this.setState({password : newValue})} />
								    		</div>
								    		
								    		<button className="btn btn-lg btn-info btn-block" type="button"  onClick={() => this.login()} >
								    		    connect <i className="fa fa-check" ></i>
								    		</button>
								    	</fieldset>
						            </div>
						        </div>
					        </div>
				       </div>
			   </div> 
		        );
			}
    }

export default LoginComponent;
