// react-frontend/src/etf/ETFComponent.js
import React, {Component} from 'react';
import axios from 'axios';


class ETFComponent extends Component {
	   
   constructor() {
            super();
			this.state = {
			        country : 'USA',
					page : 0,
					pages : 0,
					size : 0,
					cetft : '',
					cetf : null,
					content : '',
					etfs : []
				  };
       }
	   
	componentDidMount(){
            axios.get('http://localhost:8080/etfs/'+this.state.country+'/'+this.state.page).then(res => {
			   this.state.etfs = res.data.data;
			   this.state.pages = res.data.pages;
			   this.state.size = res.data.size;
			   const innerv = (<div>
						<div className="table-reponsive">
							<table className="table table-borderless">
							  <thead>
							     <tr>
								 <th>Ticker</th>
								 <th>Name</th>
								 <th>Exchange</th>
								 <th>Action</th>
								 </tr>
							  </thead>
							  <tbody>
							     {this.state.etfs.map((item,i) => { return (
										<tr key={item.ticker} >
										<td>{item.ticker}</td>
										<td>{item.name}</td>
										<td>{item.exchange}</td>
										<td>
											<button type="button"  className="btn btn-outline-info btn-sm"  onClick={this.fetch.bind(this, item.ticker)} >
												 <i className="fa fa-check" ></i>
											</button>
										</td>
									  </tr>
									);})}
							  </tbody>
							</table>
						</div>
						<nav>
						     <ul  className="pagination pagination-sm justify-content-end" >
									 <li  className="page-item disabled" >
											<button type="button"  className="page-link"  ><i className="fa fa-step-backward " ></i></button>
									  </li>
									  <li className="page-item disabled"><a className="page-link" href="#">0</a></li>
									  <li className="page-item" >
										  <button type="button"  className="page-link"  onClick={this.fetchPage.bind(this, 1)}   ><i className="fa fa-step-forward " ></i></button>
									  </li>
							</ul>
						</nav>
						</div>);
				  this.setState({content: innerv});
			 });
       }


   change(e){ 
          e.preventDefault();
          this.state.country = e.target.value;
		  this.state.page = 0;
		  axios.get('http://localhost:8080/etfs/'+this.state.country+'/'+this.state.page).then(res => {
			   this.state.etfs = res.data.data;
			   this.state.pages = res.data.pages;
			   this.state.size = res.data.size;
				const innerv =  (<div>
						<div className="table-reponsive">
							<table className="table table-borderless">
							  <thead>
							     <tr>
								 <th>Ticker</th>
								 <th>Name</th>
								 <th>Exchange</th>
								 <th>Action</th>
								 </tr>
							  </thead>
							  <tbody>
							   {this.state.etfs.map((item,i) => { return (
										<tr key={item.ticker} >
										<td>{item.ticker}</td>
										<td>{item.name}</td>
										<td>{item.exchange}</td>
										<td>
											<button type="button"  className="btn btn-outline-info btn-sm"  onClick={this.fetch.bind(this, item.ticker)} >
												 <i className="fa fa-check" ></i>
											</button>
										</td>
									  </tr>
									);})}
							  </tbody>
							</table>
						</div>
						<nav>
						     <ul  className="pagination pagination-sm justify-content-end" >
									  <li  className={(this.state.page === 0)  ?  "page-item disabled" : "page-item"}>
											<button type="button"  className="page-link" onClick={(this.state.page === 0)  ?  this.ignore : this.fetchPage.bind(this, this.state.page - 1)}   ><i className="fa fa-step-backward" ></i></button>
									  </li>
									  <li className="page-item disabled"><a className="page-link" href="#">{this.state.page}</a></li>
									  <li className={(this.state.page === this.state.pages)  ?  "page-item disabled" : "page-item"} >
										  <button type="button"  className="page-link" onClick={(this.state.page === this.state.pages)  ?  this.ignore : this.fetchPage.bind(this, this.state.page + 1)}   ><i className="fa fa-step-forward" ></i></button>
									  </li>
							</ul>
						</nav></div>);						
				  this.setState({content: innerv});
                });
    	}	



       fetchPage(page) {
          this.state.page = page;
		  axios.get('http://localhost:8080/etfs/'+this.state.country+'/'+page).then(res => {
			      this.state.etfs = res.data.data;
				  const innerv =  (<div>
						<div className="table-reponsive">
							<table className="table table-borderless">
							  <thead>
							     <tr>
								 <th>Ticker</th>
								 <th>Name</th>
								 <th>Exchange</th>
								 <th>Action</th>
								 </tr>
							  </thead>
							  <tbody>
                                   {this.state.etfs.map((item,i) => { return (
										<tr key={item.ticker} >
										<td>{item.ticker}</td>
										<td>{item.name}</td>
										<td>{item.exchange}</td>
										<td>
											<button type="button"  className="btn btn-outline-info btn-sm"  onClick={this.fetch.bind(this, item.ticker)} >
												 <i className="fa fa-check" ></i>
											</button>
										</td>
									  </tr>
									);})}
							  </tbody>
							</table>
						</div>
						<nav>
						     <ul  className="pagination pagination-sm justify-content-end" >
									  <li  className={(this.state.page === 0)  ?  "page-item disabled" : "page-item"}>
											<button type="button"  className="page-link" onClick={(this.state.page === 0)  ? this.ignore : this.fetchPage.bind(this, this.state.page - 1)}   ><i className="fa fa-step-backward " ></i></button>
									  </li>
									  <li className="page-item disabled"><a className="page-link" href="#">{this.state.page}</a></li>
									  <li className={(this.state.page === this.state.pages)  ?  "page-item disabled" : "page-item"} >
										  <button type="button"  className="page-link" onClick={(this.state.page === this.state.pages)  ?  this.ignore : this.fetchPage.bind(this, this.state.page + 1)}   ><i className="fa fa-step-forward " ></i></button>
									  </li>
							</ul>
						</nav></div>);						
				  this.setState({content: innerv});
             });
	          }	
			  
			  
			  
			  fetch(etf){
					 this.state.cetft = etf;
					  axios.get('http://localhost:8080/etf/'+etf).then(res => {
							 this.state.cetf = res.data;
		                     const infovl = <div>
								   <div  className="float-right">
								      <button type="button"  className="btn btn-outline-info btn-sm"    onClick={this.back.bind(this)} >
										 <i className="fa fa-step-backward" ></i>
									 </button>
								   </div><br/><br/>
								   <div className="card" >
									  <div className="card-body">
										<h5 className="card-title float-left">{this.state.cetf.ticker}</h5>
										<br/>
										<div className="float-left" >
											<p className="card-text float-left">Name : {this.state.cetf.name}</p><br/><br/>
											<p className="card-text float-left bottenm">Exchange : {this.state.cetf.exchange}</p><br/><br/>
											<p className="card-text float-left bottenm">Country : {this.state.cetf.country}</p><br/><br/>
											<p className="card-text float-left bottenm">Day Flow : {this.state.cetf.dayFlow} $</p><br/><br/>
											<p className="card-text float-left bottenm">Week Flow : {this.state.cetf.weekFlow} $</p><br/><br/>
											<p className="card-text float-left bottenm">Year to date Flow : {this.state.cetf.ytdFlow} $</p><br/><br/>
											<p className="card-text float-left bottenm">1 Year Flow : {this.state.cetf.y1Flow} $</p><br/><br/>
											<p className="card-text float-left bottenm" >3 Year Flow : {this.state.cetf.y3Flow} $</p><br/>
										</div>
									  </div>
									</div>
									<br/>
								   <div  className="float-right">
								     <button type="button"  className="btn btn-outline-info btn-sm"    onClick={this.back.bind(this)} >
										 <i className="fa fa-step-backward" ></i>
									 </button>
								   </div>
							   </div>;
			   this.setState({content: infovl});
		      }); 
			  }



         back(e){
			   e.preventDefault();
               this.state.cetft = '';
		       const innerv =  (<div>
						<div className="table-reponsive">
							<table className="table table-borderless">
							  <thead>
							     <tr>
								 <th>Ticker</th>
								 <th>Name</th>
								 <th>Exchange</th>
								 <th>Action</th>
								 </tr>
							  </thead>
							  <tbody>
                                   {this.state.etfs.map((item,i) => { return (
										<tr key={item.ticker} >
										<td>{item.ticker}</td>
										<td>{item.name}</td>
										<td>{item.exchange}</td>
										<td>
											<button type="button"  className="btn btn-outline-info btn-sm"  onClick={this.fetch.bind(this, item.ticker)} >
												 <i className="fa fa-check" ></i>
											</button>
										</td>
									  </tr>
									);})}
							  </tbody>
							</table>
						</div>
						<nav>
						     <ul  className="pagination pagination-sm justify-content-end" >
									  <li  className={(this.state.page === 0)  ?  "page-item disabled" : "page-item"}>
											<button className="page-link" onClick={(this.state.page === 0)  ?  this.ignore : this.fetchPage(this.state.page - 1)}   ><i className="fa fa-step-backward " ></i></button>
									  </li>
									  <li className="page-item disabled"><a className="page-link" href="#">{this.state.page}</a></li>
									  <li className={(this.state.page === this.state.pages)  ?  "page-item disabled" : "page-item"} >
										  <button className="page-link" onClick={(this.state.page === this.state.pages)  ?  this.ignore : this.fetchPage(this.state.page + 1)}   ><i className="fa fa-step-forward " ></i></button>
									  </li>
							</ul>
						</nav></div>);						
				  this.setState({content: innerv});
		       }	



   
	
	   
	    ignore = (e) => {
			e.preventDefault();
		  }
	 
	render(){
		  
		   const chtml =  this.props.ycountries.map((item,i) => 
									   <option key={item.idx} value={item.idx} >{item.value}</option>);
		  return (
		        <div>
					<div className="form-group float-right" >
						 <label>Country</label>
						 <select className="form-control"  onChange={this.change.bind(this)}   >
							  {chtml}
						 </select>
					 </div>
					 <br/><br/><br/><br/>
					 <div  className="container"  >
					     <div  className="row"  >
						       <div  className="col-md-1 col-lg-1"  >  </div>
						       <div  className="col-md-10 col-lg-10"  >
									 <div  className="card"  >
									    <div  className="card-body"  >
									        {this.state.content}
									     </div>
									 </div>
							    </div>
							    <div  className="col-md-1 col-lg-1"  >  </div>
					    </div>
					  </div>
				 </div>
		        );
			}
    }

export default ETFComponent;

// angular-frontend/src/app/etf/etf.component.ts
import { Component, OnInit } from '@angular/core';
import { Etf } from '../models/etf.model';
import { EtfService } from '../services/etf.service';

@Component({
  selector: 'app-etf',
  templateUrl: './etf.component.html',
  styleUrls: ['./etf.component.css']
})
export class EtfComponent implements OnInit {

   private countries: Array<{idx: string, value: string}>  = [{idx : "USA", value : "USA"}, 
					   {idx : "Germany", value : "Germany"},
					   {idx : "France", value : "France"}, 
					   {idx : "Australia", value : "Australia"},
					   {idx : "Indonesia", value : "Indonesia"},
					   {idx : "Canada", value : "Canada"},
					   {idx : "Belgium", value : "Belgium"},
					   {idx : "Argentina", value : "Argentina"},
					   {idx : "United Kingdom", value : "United Kingdom"},
					   {idx : "Malaysia", value : "Malaysia"},
					   {idx : "Netherlands", value : "Netherlands"},
					   {idx : "Switzerland", value : "Switzerland"},
					   {idx : "Taiwan", value : "Taiwan"},
					   {idx : "Norway", value : "Norway"},
					   {idx : "Sweden", value : "Sweden"},
					   {idx : "Denmark", value : "Denmark"},
					   {idx : "Austria", value : "Austria"},
					   {idx : "Brazil", value : "Brazil"},
					   {idx : "Singapore", value : "Singapore"},
					   {idx : "India", value : "India"},
					   {idx : "Mexico", value : "Mexico"},
					   {idx : "Ireland", value : "Ireland"},
					   {idx : "Russia", value : "Russia"},
					   {idx : "Italy", value : "Italy"}];
					   
   private page: number = 0;	
   private pages: number = 0;
   private size: number = 0;	 
   private country: string = this.countries[0].value;	
   private etf: Etf;	 
   private etfticker: string = '';	
   private etfs: Etf[];
					   
  constructor(private etfService:EtfService) { }

  ngOnInit() {
	  this.etfService.fetch(this.country, this.page)
		    .subscribe((res: any) => {
					 this.etfs = res.data;
					 this.pages = res.pages;
					 this.size = res.size;  
				 });
     }
	 
	 
	     change(e){
		   this.country = e.target.value;
		   this.page = 0;
		   this.etfticker = '';
		   this.etfs = null;
		   this.etf = null;
		   this.etfService.fetch(this.country, this.page)
			.subscribe((res: any) => {
				    console.log(res);
					 this.etfs = res.data;
					 this.pages = res.pages;
					 this.size = res.size;  
				 });
           }	 
	 
	    fetch(page){
		   this.page = page;
		   this.etfticker = '';
		   this.etfs = null;
		   this.etf = null;
		   this.etfService.fetch(this.country, this.page)
			.subscribe((res: any) => {
				     console.log(res);
					 this.etfs = res.data;
					 this.pages = res.pages;
					 this.size = res.size; 
				 });
           } 
		   
		   
         fetchetf(etf){
			  this.etfticker = etf;
	          this.etfService.fetchetf(this.etfticker)
			      .subscribe((res: any) => {
					 this.etf = res;
				 });
           }
		   
		   
		   
		    back(){
		    this.etf = null;
                  }


        
	 

}

     <div>
		<div class="form-group float-right" >
			 <label>Country</label>
			 <select class="form-control"  (change)="change($event)"   >
				  <option  *ngFor="let c of countries"  value="{{c.idx}}"  >{{c.value}}</option>
			 </select>
		 </div>
		 <br/><br/><br/><br/>
		 <div  class="container"  >
			 <div  class="row"  >
				   <div  class="col-md-1 col-lg-1"  >  </div>
				   <div  class="col-md-10 col-lg-10"  >
						 <div  *ngIf="etfs && !etf" class="card"  >
							<div  class="card-body"  >
								<div>
									<div class="table-reponsive">
										<table class="table table-borderless">
										  <thead>
											 <tr>
											 <th>Ticker</th>
											 <th>Name</th>
											 <th>Exchange</th>
											 <th>Action</th>
											 </tr>
										  </thead>
										  <tbody>
											   <tr *ngFor="let e of etfs"  >
													<td>{{e.ticker}}</td>
													<td>{{e.name}}</td>
													<td>{{e.exchange}}</td>
													<td>
														<button type="button"  class="btn btn-outline-info btn-sm"  (click)="fetchetf(e.ticker)" >
															 <i class="fa fa-check" ></i>
														</button>
													</td>
												</tr>
										  </tbody>
										</table>
									</div>
									<nav>
										 <ul  class="pagination pagination-sm justify-content-end" >
												  <li [ngClass]="(page == 0 || pages == 0) ? 'page-item disabled' : 'page-item'" >
														<a class="page-link"    (click)="fetch(page - 1)"   ><i class="fa fa-step-backward " ></i></a>
												  </li>
												  <li class="page-item disabled"><a class="page-link" href="#">{{page}}</a></li>
												  <li [ngClass]="(page == pages || pages == 0) ? 'page-item disabled' : 'page-item'" >
													  <a class="page-link" (click)="fetch(page + 1)"   ><i class="fa fa-step-forward " ></i></a>
												  </li>
										</ul>
									 </nav>
			                    </div>
							 </div>
						 </div>
						 <div   *ngIf="etf" >
							<div  class="float-right">
								      <button type="button"  class="btn btn-outline-info btn-sm"  (click)="back()" >
										 <i class="fa fa-step-backward" ></i>
									 </button>
								   </div><br/><br/>
								   <div class="card" >
									  <div class="card-body">
										<h5 class="card-title float-left">{{etf.ticker}}</h5>
										<br/>
										<div class="float-left" >
											<p class="card-text">Name : {{etf.name}}</p>
											<p class="card-text">Exchange : {{etf.exchange}}</p>
											<p class="card-text">Country : {{etf.country}}</p>
											<p class="card-text">Day Flow :   <span   [ngClass]="(etf.dayFlow > 0) ? 'grennvl' : 'redvl'"  >{{etf.dayFlow}} </span> $</p>
											<p class="card-text">Week Flow : <span   [ngClass]="(etf.weekFlow > 0) ? 'grennvl' : 'redvl'"  >{{etf.weekFlow}} </span> $</p>
											<p class="card-text">Year to date Flow : <span [ngClass]="(etf.ytdFlow > 0) ? 'grennvl' : 'redvl'"  >{{etf.ytdFlow}} </span> $</p>
											<p class="card-text">1 Year Flow : <span [ngClass]="(etf.y1Flow > 0) ? 'grennvl' : 'redvl'"  >{{etf.y1Flow}} </span> $</p>
											<p class="card-text">3 Year Flow : <span   [ngClass]="(etf.y3Flow > 0) ? 'grennvl' : 'redvl'"  >{{etf.y3Flow}} </span> $</p>
										</div>
									  </div>
									</div>
									<br/>
								   <div  class="float-right">
								      <button type="button"  class="btn btn-outline-info btn-sm"  (click)="back()" >
										 <i class="fa fa-step-backward" ></i>
									 </button>
								   </div>
							   </div>
					</div>
					<div  class="col-md-1 col-lg-1"  >  </div>
			</div>
		  </div>
	</div>
