// angular-frontend/src/app/component/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
  
  
  logout(e){
		localStorage.removeItem("jwt");
		localStorage.removeItem("expire");
		       }

}

<nav className="navbar navbar-light bg-light"  *ngIf="auth" >
   <span className="navbar-brand mb-0 h1">Gallery</span>
   <ul className="navbar-nav ml-auto">
	   <li className="nav-item">
		 <a className="nav-link"   (click)="logout()"  >Logout</a>
	   </li>
	</ul>
</nav>  : 
<nav className="navbar navbar-light bg-light"  *ngIf="!auth"  >
   <span className="navbar-brand mb-0 h1">Gallery</span>
</nav>

// react-frontend/src/component/navbar/NavbarComponent.js
import React, {Component} from 'react';


class NavbarComponent extends Component {
   
   
     logout(e){
				localStorage.removeItem("jwt");
				//localStorage.removeItem("expire");
				let msg = 	<div  className="text-center" style="padding-top: 10px;">
								  <span  className="text-center grnvl" >Logged out</span>
							</div>;
				this.props.check(true);				
		       }
			   
			   
	   
			   		   
   
	render(){	
		  return (!(localStorage.getItem("jwt") == null) ? 
		                     <nav className="navbar navbar-light bg-light">
						   <span className="navbar-brand mb-0 h1">Gallery</span>
						   <ul className="navbar-nav ml-auto">
							   <li className="nav-item">
								 <a className="nav-link" onClick={() => this.logout()}  href="#">Logout</a>
							   </li>
							</ul>
					   </nav>  : 
					    <nav className="navbar navbar-light bg-light">
						   <span className="navbar-brand mb-0 h1">Gallery</span>
					   </nav> );
		}
    }

export default NavbarComponent;
